version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com  # Default admin email
      - PGADMIN_DEFAULT_PASSWORD=admin           # Default admin password
    ports:
      - "8080:80"                                # Expose pgAdmin on port 8080
    depends_on:
      - postgres

volumes:
  postgres-data:
