# run: docker compose -f portainer-docker-compose.yml -p "portainer-stack" up -d
version: "3.9"
services:
  portainersrv:
    container_name: portainer_ctr
    restart: always
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
    volumes:
      - /portainer_data
      - /var/run/docker.sock:/var/run/docker.sock